version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=311037684946.dkr.ecr.us-east-1.amazonaws.com/sre-demo-app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker --version
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"sreapp","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
      - curl -LO https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl
      - mv kubectl /usr/bin
      - chmod +x /usr/bin/kubectl
      - aws eks update-kubeconfig --region us-east-1 --name sre-demo-cluster
      - kubectl config get-context
      - kubectl apply -f sre-deployment.yaml
artifacts:  
  files: imagedefinitions.json